exports.auth = async ( ) => {
    try{

    }catch(err) =>{
        console.log(err)
    }
}